In [1]:
import pandas as pd
import numpy as np
import os

from encoding_function import low_frequency_to_others
from sklearn.model_selection import KFold
from category_encoders import TargetEncoder
from sklearn.preprocessing import OneHotEncoder
from catboost_function import custom_CatBoostClassifier

import warnings
warnings.filterwarnings('ignore')

### 데이터 불러오기

In [2]:
def add_y(df):
    df['rank'] = df['rank'].replace(0, 6)

    target_cols = [
        '단승', '복승', '삼복승'
    ]
    for i, col in enumerate(target_cols):
        condition_target = df['rank'] <= i+1
        df.loc[condition_target, col] = 1

    df[target_cols] = df[target_cols].fillna(0)
    df.drop(['rank'], axis=1, inplace=True)
    return df

def add_y_(df):
    df['rank'] = df['rank'].replace(0, 6)

    target_cols = [
        '단승', '복승', '삼복승'
    ]
    for i, col in enumerate(target_cols):
        condition_target = df['rank'] <= i+1
        df.loc[condition_target, col] = df['rank']

    df[target_cols] = df[target_cols].fillna(0)
    df.drop(['rank'], axis=1, inplace=True)
    return df



ROOT_DIR = "data"
RANDOM_STATE = 42

train = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))
test = pd.read_csv(os.path.join(ROOT_DIR, "test.csv"))

train['성별'] = train['성별'].map({'남': 0, '여': 1})
test['성별'] = test['성별'].map({'남': 0, '여': 1})

train = add_y(train)
test = add_y(test)

print(train.shape, test.shape)
train.head()

(58344, 46) (6528, 46)

,Race_ID,연도,회차,일차,경주번호,경기종류,번호,등급,기수,선수명,...,모터_연대율3,전탑승선수1,전탑승선수2,보트번호,보트_평균착순점,보트_연대율,특이사항,단승,복승,삼복승
0,2016_1_1_1,2016,1,1,1,플라잉,1,A1,1,정용진,...,0.0,NaN,NaN,27,0.0,0.0,NaN,0.0,0.0,1.0
1,2016_1_1_1,2016,1,1,1,플라잉,2,A1,13,김민준,...,0.0,NaN,NaN,50,0.0,0.0,NaN,1.0,1.0,1.0
2,2016_1_1_1,2016,1,1,1,플라잉,3,B2,11,김현덕,...,0.0,NaN,NaN,71,0.0,0.0,주선보류 후 출전,0.0,0.0,0.0
3,2016_1_1_1,2016,1,1,1,플라잉,4,A1,8,한종석,...,0.0,NaN,NaN,53,0.0,0.0,NaN,0.0,1.0,1.0
4,2016_1_1_1,2016,1,1,1,플라잉,5,B1,9,정재용,...,0.0,NaN,NaN,64,0.0,0.0,NaN,0.0,0.0,0.0

In [3]:
def add_weight_penalty(df):
    weight_limit_male = 55
    weight_limit_female = 51
    df['체중'] = df['체중'].astype(float)
    
    # 중량 부과 여부 계산 (성별에 따라 다른 기준 적용)
    df['중량부과여부'] = df.apply(lambda row: 1 if (row['성별'] == 0 and row['체중'] < weight_limit_male) or
                                             (row['성별'] == 1 and row['체중'] < weight_limit_female) else 0, axis=1)

    # 부과된 중량 계산 (성별에 따라 차감된 체중을 계산)
    df['부과된중량'] = df.apply(lambda row: max(0, weight_limit_male - row['체중']) if row['성별'] == 0 else
    max(0, weight_limit_female - row['체중']), axis=1)
    
    df.drop('체중', axis=1, inplace=True)

    return df

train = add_weight_penalty(train)
test = add_weight_penalty(test)

In [4]:
def bin_age(df):
    # 나이를 5개 구간으로 나누어 bin화 (예: 0-20, 20-30, 30-40, 40-50, 50+)
    bins = [20, 30, 40, 50, 100]
    labels = ['20-30', '30-40', '40-50', '50+']

    # 나이 변수를 bin화
    df['나이'] = pd.cut(df['나이'], bins=bins, labels=labels, right=False)

    map_age = {
        '20-30':25,
        '30-40':35,
        '40-50':45,
        '50+':55,
    }
    df['나이'] = df['나이'].map(map_age)

    return df

train = bin_age(train)
test = bin_age(test)

## 사용하지 않는 feature drop

In [5]:
def drop_columns_from_datasets(df):
    drop_cols = [
        '연도', '회차', '일차', '경주번호', # 일차도 제거?
        '금일출주경주',
        '모터번호', '전탑승선수1', '전탑승선수2',
        '보트번호', '특이사항',
        'FL' # F뒤의 숫자는 현재 반기의 실격 횟수, L뒤의 숫자는 반칙횟수?
    ]

    df = df.drop(drop_cols, axis=1)

    return df


train = drop_columns_from_datasets(train)
test = drop_columns_from_datasets(test)

print(train.shape, test.shape)

(58344, 36) (6528, 36)

In [6]:
def reverse_rank_values(df_train, df_val):
    cols_to_reverse = [
        '최근6회차_평균착순점', '최근6회차_평균득점',
        '연간성적_평균착순점',
        '모터_평균착순점',
        '보트_평균착순점'
    ]
    for col in cols_to_reverse:
        max_rank = df_train[col].max()
        df_train[col] = max_rank - df_train[col]
        df_val[col] = max_rank - df_val[col]
    
        df_train[col].fillna(0, inplace=True)
        df_val[col].fillna(0, inplace=True)
    
    return df_train, df_val


train, test = reverse_rank_values(train, test)

In [7]:
import re

def extract_numbers(result):
    if isinstance(result, str):  # result가 문자열인 경우에만 처리
        return re.findall(r'-(\d+)-', result)  # -숫자- 형식에서 중간 숫자 추출
    return []  # 문자열이 아니면 빈 리스트 반환

def calculate_mean(numbers):
    numbers = [int(num) for num in numbers]  # 리스트 안의 문자열 숫자를 정수로 변환
    if len(numbers) > 0:
        return np.mean(numbers)  # 리스트가 비어있지 않으면 평균 계산
    else:
        return np.nan  # 빈 리스트인 경우 NaN 반환

def last_race_process(df_train, df_val):
    df_train['전일성적'] = df_train['전일성적'].apply(extract_numbers)  # 순위만 추출 (코스도 같이 추출?)
    df_train['전일성적'] = df_train['전일성적'].apply(calculate_mean) # 평균 계산

    df_val['전일성적'] = df_val['전일성적'].apply(extract_numbers)
    df_val['전일성적'] = df_val['전일성적'].apply(calculate_mean)

    max_rank = df_train['전일성적'].max()
    df_train['전일성적'] = max_rank - df_train['전일성적'] + 1
    df_val['전일성적'] = max_rank - df_val['전일성적'] + 1
    
    df_train['전일성적'].fillna(1, inplace=True)
    df_val['전일성적'].fillna(1, inplace=True)
    
    return df_train, df_val

train, test = last_race_process(train, test)

## 일부 숫자형 변수 변환

- 코스별 성적/경기수 분리

In [8]:
def separation_course(df):
    col_list = [
        '코스_1코스', '코스_2코스', '코스_3코스', '코스_4코스', '코스_5코스', '코스_6코스'
    ]
    for col in col_list:
        df[[f'{col[3:]}_성적', f'{col[3:]}_경기수']] = df[col].fillna('').str.split('/', expand=True)

    df.drop(col_list, axis=1, inplace=True)

    return df
        


train = separation_course(train)
test = separation_course(test)

print(train.shape, test.shape)

(58344, 42) (6528, 42)

- 코스별 성적 스무딩

In [9]:
def apply_laplace_smoothing(df, col, global_mean, alpha):
    # 경기수 0인 값이 너무 높게 나오는 경향이 있어 분모에 상수 1 추가(없애도 됨)
    encoded_value = (df[f'{col}_성적'] * df[f'{col}_경기수'] + global_mean * alpha) / (1 + df[f'{col}_경기수'] + alpha)
    df[f'{col}_성적'] = encoded_value

    return df

def laplace_smoothing_to_course(train, val=None, alpha=1):
    col_list = [
        '1코스', '2코스', '3코스', '4코스', '5코스', '6코스'
    ]
    for col in col_list:
        train[f'{col}_성적'] = train[f'{col}_성적'].astype(float)
        train[f'{col}_경기수'] = train[f'{col}_경기수'].astype(float)
        if val is not None:
            val[f'{col}_성적'] = val[f'{col}_성적'].astype(float)
            val[f'{col}_경기수'] = val[f'{col}_경기수'].astype(float)

    # Train 데이터에서 글로벌 평균 계산
    global_means = {col: train[f'{col}_성적'].mean() for col in col_list}

    for col in col_list:
        # Train 데이터에 라플라스 스무딩 적용
        train = apply_laplace_smoothing(train, col, global_means[col], alpha)
        train.drop(f'{col}_경기수', axis=1, inplace=True)

    if val is not None:
        for col in col_list:
            # Validation 데이터에 Train에서 구한 글로벌 평균으로 라플라스 스무딩 적용
            val = apply_laplace_smoothing(val, col, global_means[col], alpha)
            val.drop(f'{col}_경기수', axis=1, inplace=True)

    if val is not None:
        return train, val
    else:
        return train


train, test = laplace_smoothing_to_course(train, test, alpha=1) # 알파가 작을수록 빈도수에 가깝세, 알파가 클수록 전체 평균에 가깝게
print(train.shape, test.shape)

(58344, 36) (6528, 36)

In [10]:
def set_course_scores(df):
    # '코스_성적' 열을 초기화
    df['코스_성적'] = 0

    # '번호' 열에 따른 '코스_성적' 값 설정
    for i in range(1, 7):
        mask = df['번호'] == i
        df.loc[mask, '코스_성적'] = df.loc[mask, f'{i}코스_성적']

    # 제거할 열 목록
    drop_cols = [f'{i}코스_성적' for i in range(1, 7)]

    # 열 제거
    df = df.drop(columns=drop_cols)

    return df


from sklearn.decomposition import PCA
def apply_pca(df_train, df_val, n_components=2):
    course_cols = [f'{i}코스_성적' for i in range(1, 7)]

    pca = PCA(n_components=n_components)
    pca.fit(df_train[course_cols])

    # 훈련 데이터에 PCA 변환 적용 (transform)
    train_pca = pca.transform(df_train[course_cols])
    val_pca = pca.transform(df_val[course_cols])
    for i in range(n_components):
        col_name = f'PCA_코스성적_{i+1}'
        df_train[col_name] = train_pca[:, i]
        df_val[col_name] = val_pca[:, i]

    # 각 컴포넌트별 분산 설명 비율 출력
    # explained_variance_ratios = pca.explained_variance_ratio_
    # for i, ratio in enumerate(explained_variance_ratios):
    #     print(f"PCA Component {i+1}: {ratio:.4f} variance explained")
    
    # n_components=2가 제일 좋아보임

    return df_train, df_val


train, test = apply_pca(train, test, n_components=2)
train = set_course_scores(train)
test = set_course_scores(test)

- 최근 8경기 착순 분리

In [11]:
def split_last_eight_rank(df):
    for i in range(0, 4):
        df[f'최근{i+1}경기_착순'] = df['최근8경주_착순'].str[i]
    for j in range(5, 9):
        df[f'최근{j}경기_착순'] = df['최근8경주_착순'].str[j]
        
    df.drop('최근8경주_착순', axis=1, inplace=True)
    
    return df

# def adjust_for_top3(df):
#     col_list = [
#         '최근1경기_착순', '최근2경기_착순', '최근3경기_착순', '최근4경기_착순',
#         '최근5경기_착순', '최근6경기_착순', '최근7경기_착순', '최근8경기_착순'
#     ]
# 
#     for col in col_list:
#     # 순위가 1, 2, 3이 아닌 경우, 결측인 경우, 6으로 조정
#     # (일반화된 성능을 위해 + 3등내에 드는게 중요)
#         df[col] = df[col].apply(lambda x: x if x in ['1', '2', '3'] else '-1')
# 
#     return df

def adjust_last_eight_rank(df_train, df_val):
    col_list = [
        '최근1경기_착순', '최근2경기_착순', '최근3경기_착순', '최근4경기_착순',
        '최근5경기_착순', '최근6경기_착순', '최근7경기_착순', '최근8경기_착순'
    ]

    for col in col_list:
        df_train[col] = df_train[col].fillna(6).astype(int)
        df_val[col] = df_val[col].fillna(6).astype(int)
        
        # df_train[col] = df_train[col].replace(0, 1)  # 가끔씩 0이 있는 경우가 존재
        # df_val[col] = df_val[col].replace(0, 1)
        # 그냥 냅두는게 성능이 젤 높음

        max_rank = df_train[col].max()
        df_train[col] = max_rank - df_train[col]
        df_val[col] = max_rank - df_val[col]
    
    first_mean_cols = 3
    col_to_mean_1 = col_list[:first_mean_cols]

    df_train[f'최근{first_mean_cols}경기_평균'] = df_train[col_to_mean_1].mean(axis=1)
    df_val[f'최근{first_mean_cols}경기_평균'] = df_val[col_to_mean_1].mean(axis=1)

    df_train.drop(col_list, axis=1, inplace=True)
    df_val.drop(col_list, axis=1, inplace=True)

    return df_train, df_val


train = split_last_eight_rank(train)
# train = adjust_for_top3(train)

test = split_last_eight_rank(test)
# test = adjust_for_top3(test)

train, test = adjust_last_eight_rank(train, test)

print(train.shape, test.shape)

(58344, 33) (6528, 33)

In [12]:
def encode_categorical_features(df_train, df_val, target_value='복승'):
    df_train['번호_등급'] = df_train['번호'].astype(str) + df_train['등급'].astype(str)
    df_val['번호_등급'] = df_val['번호'].astype(str) + df_val['등급'].astype(str)
    
    target_encoder = TargetEncoder(smoothing=2)
    target_encoder.fit(df_train['번호_등급'], df_train[target_value])
    
    df_train['등급'] = target_encoder.transform(df_train['번호_등급'])
    df_val['등급'] = target_encoder.transform(df_val['번호_등급'])
    
    df_train.drop('번호_등급', axis=1, inplace=True)
    df_val.drop('번호_등급', axis=1, inplace=True)
    
    train_racetype = df_train[['경기종류']].copy()
    val_racetype = df_val[['경기종류']].copy()

    train_racetype[['플라잉', '온라인']] = 0
    val_racetype[['플라잉', '온라인']] = 0
    
    train_racetype.loc[train_racetype['경기종류']=='플라잉', '플라잉'] = 1
    train_racetype.loc[train_racetype['경기종류']=='온라인', '온라인'] = 1

    val_racetype.loc[val_racetype['경기종류']=='플라잉', '플라잉'] = 1
    val_racetype.loc[val_racetype['경기종류']=='온라인', '온라인'] = 1

    train_racetype.drop('경기종류', axis=1, inplace=True)
    val_racetype.drop('경기종류', axis=1, inplace=True)
    
    df_train = pd.concat([train_racetype, df_train], axis=1)
    df_val = pd.concat([val_racetype, df_val], axis=1)
    
    df_train.drop('경기종류', axis=1, inplace=True)
    df_val.drop('경기종류', axis=1, inplace=True)
    
    return df_train, df_val

train, test = encode_categorical_features(train, test)
train

,플라잉,온라인,Race_ID,번호,등급,기수,선수명,성별,나이,최근6회차_평균착순점,...,보트_연대율,단승,복승,삼복승,중량부과여부,부과된중량,PCA_코스성적_1,PCA_코스성적_2,코스_성적,최근3경기_평균
0,1,0,2016_1_1_1,1,0.755632,1,정용진,0,45,3.33,...,0.0,0.0,0.0,1.0,0,0.0,16.574134,23.135649,72.466565,5.000000
1,1,0,2016_1_1_1,2,0.633299,13,김민준,0,25,3.83,...,0.0,1.0,1.0,1.0,0,0.0,36.239415,-14.821515,67.503244,4.666667
2,1,0,2016_1_1_1,3,0.219374,11,김현덕,0,35,6.69,...,0.0,0.0,0.0,0.0,0,0.0,-29.709277,-2.637123,15.483830,2.000000
3,1,0,2016_1_1_1,4,0.451251,8,한종석,0,35,3.14,...,0.0,0.0,1.0,1.0,0,0.0,39.980929,-28.473963,35.617032,4.666667
4,1,0,2016_1_1_1,5,0.181429,9,정재용,0,35,5.94,...,0.0,0.0,0.0,0.0,0,0.0,-17.803091,3.856657,3.421800,1.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58339,1,0,2023_52_2_17,2,0.373120,1,김국흠,0,55,5.17,...,29.4,0.0,0.0,1.0,0,0.0,-23.509572,24.573374,5.746564,1.333333
58340,1,0,2023_52_2_17,3,0.388318,7,배혜민,0,45,4.21,...,32.1,0.0,0.0,0.0,0,0.0,29.011377,5.689561,36.807518,4.000000
58341,1,0,2023_52_2_17,4,0.324412,12,김인혜,1,35,4.26,...,26.1,0.0,1.0,1.0,0,0.0,18.544591,27.481776,15.950548,2.333333
58342,1,0,2023_52_2_17,5,0.142238,15,엄광호,0,35,6.56,...,30.7,0.0,0.0,0.0,0,0.0,-42.750123,-3.619043,3.421800,0.666667
58343,1,0,2023_52_2_17,6,0.172218,10,김태규,0,35,5.13,...,39.1,0.0,0.0,0.0,0,0.0,3.836977,17.453472,1.560071,2.000000

## 범주형 변수 확인

In [13]:
def cal_cat_cols(train, val=None):
    objective_cols = []

    # 특정 문자열이 포함된 열을 범주형 변수로 지정
    # cat_kerword_list = ['번호', '기수', '경기_착순']
    cat_kerword_list = ['번호', '경기종류', 'Race_ID']
    for col in train.columns:
        if any(sub in col for sub in cat_kerword_list):
            objective_cols.append(col)
            train[col] = train[col].astype('str')
            val[col] = val[col].astype('str')
            
    # 나머지 열에 대해 숫자형 변환 시도
    for col in train.columns:
        if col in objective_cols:
            continue  # 이미 범주형으로 처리된 열은 제외
        try:
            # 'float' 타입으로 변환 시도
            train[col] = train[col].astype('float')
            val[col] = val[col].astype('float')
        except:
            objective_cols.append(col)

    cat_features = list(set(objective_cols) - set(['rank', 'Race_ID']))
    cat_features = [feature for feature in cat_features if '단승' not in feature]
    cat_features = [feature for feature in cat_features if '복승' not in feature]
    cat_features = [feature for feature in cat_features if '삼복승' not in feature]

    return cat_features


cat_features = cal_cat_cols(train, test)
cat_features

['번호', '선수명']

## X, y 분리

In [14]:
drop_cols = [
    'Race_ID', '번호', '단승', '복승', '삼복승', '선수명', '기수', '플라잉', '온라인'
]

train_type = train[['Race_ID', '플라잉', '온라인']]  # 일차까지?
X_train = train.drop(drop_cols, axis=1)
y_train = train[['단승']]

test_type = test[['Race_ID', '플라잉', '온라인']]
X_test = test.drop(drop_cols, axis=1)
y_test = test[['단승']]

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(58344, 25) (58344, 1) (6528, 25) (6528, 1)

In [15]:
def reshape_race_data(df, players_per_race=6):
    # numpy 배열로 변환
    values = df.values

    # 데이터 형태 변환 (6개의 행을 1개의 행으로)
    reshaped_values = values.reshape(-1, players_per_race * values.shape[1])

    # 새로운 컬럼 이름 생성
    columns = [f'{col}_{i+1}번선수' for i in range(players_per_race) for col in df.columns]

    # 재구성된 DataFrame 생성
    reshaped_df = pd.DataFrame(reshaped_values, columns=columns)

    return reshaped_df

X_train = reshape_race_data(X_train, players_per_race=6)
y_train = reshape_race_data(y_train, players_per_race=6)
y_train = np.array(y_train).astype(int)

X_test = reshape_race_data(X_test, players_per_race=6)
y_test = reshape_race_data(y_test, players_per_race=6)
y_test = np.array(y_test).astype(int)

train_type.drop_duplicates(inplace=True)
test_type.drop_duplicates(inplace=True)

train_type = train_type.reset_index(drop=True)
test_type = test_type.reset_index(drop=True)

X_train = pd.concat([train_type, X_train], axis=1)
X_test = pd.concat([test_type, X_test], axis=1)

X_train.drop('Race_ID', axis=1, inplace=True)
X_test.drop('Race_ID', axis=1, inplace=True)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(9724, 152) (9724, 6) (1088, 152) (1088, 6)

In [16]:
def low_to_others(train, val, threshold=5, is_train=True, verbose=False):
    cat_features = cal_cat_cols(train, val)
    if is_train==False:
        cat_features = list(set(cat_features) - set(['Race_ID_1번선수', 'Race_ID_2번선수', 'Race_ID_3번선수', 'Race_ID_4번선수', 'Race_ID_5번선수', 'Race_ID_6번선수']))

    for col in cat_features:
        unifier = low_frequency_to_others(threshold=threshold, verbose=verbose)
        train[col] = unifier.fit_transform(train[col])
        val[col] = unifier.transform(val[col])

    return train, val

X_train, X_test = low_to_others(X_train, X_test, threshold=5, verbose=True)

In [44]:
def all_process(train, val, target='단승', is_train=True, is_dddd=False):
    train['성별'] = train['성별'].map({'남': 0, '여': 1})
    val['성별'] = val['성별'].map({'남': 0, '여': 1}) # 성별 mapping 남:0, 여:1
     
    train = add_y(train)
    if is_train:
        if is_dddd:
            val = add_y_(val)
        else:
            val = add_y(val)
            
    # train = add_weight_penalty(train) # 중량부과여부, 부과된 중량 추가 / 체중은 drop
    # val = add_weight_penalty(val) # 연승 정확도를 높이려면 제거

    # train = bin_age(train) # 나이 binning
    # val = bin_age(val)
    
    train = drop_columns_from_datasets(train)
    val = drop_columns_from_datasets(val)

    train, val = last_race_process(train, val) # 전일 성적 평균 추가

    train, val = reverse_rank_values(train, val) # 착순 관련 데이터 reverse

    train = separation_course(train)
    val = separation_course(val)

    train, val = laplace_smoothing_to_course(train, val, alpha=1)

    train, val = apply_pca(train, val, n_components=2) # 코스별 성적 pca + 해당 코스만 남김
    train = set_course_scores(train)
    val = set_course_scores(val) 
    
    train = split_last_eight_rank(train)
    # train = adjust_for_top3(train)
    
    val = split_last_eight_rank(val)
    # val = adjust_for_top3(val)

    train, val = adjust_last_eight_rank(train, val) # 최근 8경기 중 3개는 평균, 나머지 버림

    train, val = encode_categorical_features(train, val)

    if is_train:
        drop_cols = [
            'Race_ID', '번호', '단승', '복승', '삼복승', '선수명', '기수', '플라잉', '온라인'
        ]
    else:
        drop_cols = [
            'Race_ID', '번호', '선수명', '기수', '플라잉', '온라인'
        ]

    train_type = train[['Race_ID', '플라잉', '온라인']]  # 일차까지? 
    val_type = val[['Race_ID', '플라잉', '온라인']]
    
    X_train = train.drop(drop_cols, axis=1)
    y_train = train[[target]]
    X_train = reshape_race_data(X_train, players_per_race=6)
    y_train = reshape_race_data(y_train, players_per_race=6)
    # y_train = np.array(y_train).astype(int)

    X_val = val.drop(drop_cols, axis=1)
    X_val = reshape_race_data(X_val, players_per_race=6)
    if is_train:
        y_val = val[[target]]
        y_val = reshape_race_data(y_val, players_per_race=6)
        # y_val = np.array(y_val).astype(int)

    train_type.drop_duplicates(inplace=True)
    val_type.drop_duplicates(inplace=True)
    
    train_type = train_type.reset_index(drop=True)
    val_type = val_type.reset_index(drop=True)
    
    X_train = pd.concat([train_type, X_train], axis=1)
    X_val = pd.concat([val_type, X_val], axis=1)
    
    X_train.drop('Race_ID', axis=1, inplace=True)
    X_val.drop('Race_ID', axis=1, inplace=True)

    X_train, X_val = low_to_others(X_train, X_val, threshold=5, is_train=is_train, verbose=False)
    
    if is_train:
        return X_train, y_train, X_val, y_val
    else:
        return X_train, y_train, X_val
    
    
def cal_y_val_for_연승(train, test):
    df_train = train.copy()
    df_test = test.copy()
    _, _, _, y_val = all_process(df_train, df_test, target='복승', is_train=True)
    
    return y_val
    
    
train = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))
test = pd.read_csv(os.path.join(ROOT_DIR, "test.csv"))

target_value = '복승'
seed = 42

X_train, y_train, X_test, y_test = all_process(train, test, target=target_value, is_train=True)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(9724, 146) (9724, 6) (1088, 146) (1088, 6)

In [45]:
for i in range(6):
    y_i = y_train.iloc[:, i]  # i번째 레이블에 대한 y 값
    value_counts = y_i.value_counts(normalize=True)

    # 다수 클래스의 비율을 1로 고정시키고, 다른 클래스들은 상대적으로 표현
    max_class = value_counts.max()  # 다수 클래스의 비율 (가장 큰 비율)
    scaled_value_counts = value_counts / max_class  # 다수 클래스를 1로 고정

    print(f"레이블 {i+1}의 클래스 비율 (다수 클래스를 1로 고정):")
    print(scaled_value_counts)
    print("-" * 40)

레이블 1의 클래스 비율 (다수 클래스를 1로 고정):
복승_1번선수
1.0    1.000000
0.0    0.755552
Name: proportion, dtype: float64
----------------------------------------
레이블 2의 클래스 비율 (다수 클래스를 1로 고정):
복승_2번선수
0.0    1.000000
1.0    0.758727
Name: proportion, dtype: float64
----------------------------------------
레이블 3의 클래스 비율 (다수 클래스를 1로 고정):
복승_3번선수
0.0    1.000000
1.0    0.505729
Name: proportion, dtype: float64
----------------------------------------
레이블 4의 클래스 비율 (다수 클래스를 1로 고정):
복승_4번선수
0.0    1.000000
1.0    0.410502
Name: proportion, dtype: float64
----------------------------------------
레이블 5의 클래스 비율 (다수 클래스를 1로 고정):
복승_5번선수
0.0    1.000000
1.0    0.281666
Name: proportion, dtype: float64
----------------------------------------
레이블 6의 클래스 비율 (다수 클래스를 1로 고정):
복승_6번선수
0.0    1.000000
1.0    0.179668
Name: proportion, dtype: float64
----------------------------------------

In [50]:
from ctgan import CTGAN

# ctgan_list = []
# for i in range(6):
#     y_i = y_train.iloc[:, i]  # i번째 레이블에 대한 y 값

#     Xy_train = pd.concat([X_train, y_i], axis=1)
#     ctgan = CTGAN(batch_size=600, discriminator_steps=1, verbose=True, epochs=100, pac=1, cuda=True)

#     cat_features = Xy_train.columns[Xy_train.columns.str.contains('성별|등급|나이|복승')].tolist()
#     # cat_features = Xy_train.columns[Xy_train.columns.str.contains('복승')].tolist()
#     print(cat_features)

#     ctgan.fit(Xy_train, discrete_columns=cat_features)
#     ctgan_list.append(ctgan)
    
# print(len(ctgan_list))

Xy_train = pd.concat([X_train, y_train], axis=1)
cat_features = Xy_train.columns[Xy_train.columns.str.contains(f'플라잉|온라인|성별|등급|{target_value}')].tolist()
ctgan = CTGAN(batch_size=600, discriminator_steps=1, verbose=True, epochs=300, pac=1, cuda=True)
ctgan.fit(Xy_train, discrete_columns=cat_features)

target_cols = Xy_train.columns[Xy_train.columns.str.contains(f'{target_value}')].tolist()

Gen. (-0.03) | Discrim. (-0.27): 100%|███████████████████████████████████████████████| 300/300 [14:03<00:00,  2.81s/it]

In [71]:
target_cols = Xy_train.columns[Xy_train.columns.str.contains(f'{target_value}')].tolist()

new_data = ctgan.sample(3000)
condition = new_data[target_cols].sum(axis=1) == 2
new_data.loc[condition, target_cols[5]].value_counts()

복승_6번선수
0.0    1471
1.0     220
Name: count, dtype: int64

In [19]:
from catboost_function import cal_params
from catboost_function import custom_CatBoostClassifier
from catboost_function import evaluate_
from rf_function import custom_randomforest, cal_rf_params

## CatBoost

In [37]:
train = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))

params_list = cal_params(target_value=target_value, seed=seed)

unique_race_ids = train['Race_ID'].unique()
kf = KFold(n_splits=5, shuffle=True, random_state=seed)

models_cb = []
scores = []
for i, (train_race_ids, val_race_ids) in enumerate(kf.split(unique_race_ids)):
    train_ids = unique_race_ids[train_race_ids]
    val_ids = unique_race_ids[val_race_ids]

    train_fold = train[train['Race_ID'].isin(train_ids)].reset_index(drop=True)
    val_fold = train[train['Race_ID'].isin(val_ids)].reset_index(drop=True)

    X_train, y_train, X_val, y_val = all_process(train_fold, val_fold, target=target_value, is_train=True)
    
    model = custom_CatBoostClassifier(params_list)
    cat_features = cal_cat_cols(X_train, X_val)
    if i ==0:
        print('범주형 변수: ')
        print(cat_features)
    
    model.fit(X_train, y_train)

    models_cb.append(model)
    y_pred = models_cb[i].predict_proba(X_val)
    accuracy = evaluate_(y_pred, y_val, target_value)
    scores.append(accuracy)
    print(f'folds {i+1}')
    print(f'Accuracy: {accuracy}')


print(f'최종 스코어: Avg. Accuracy of validset: {np.mean(scores)}, Std. Accuracy of validset: {np.std(scores)}')

범주형 변수:
[]
folds 1
Accuracy: 0.2796915167095116
folds 2
Accuracy: 0.2802056555269923
folds 3
Accuracy: 0.27197943444730077
folds 4
Accuracy: 0.28226221079691516
folds 5
Accuracy: 0.27829218106995884
최종 스코어: Avg. Accuracy of validset: 0.27848619971013566, Std. Accuracy of validset: 0.0034940868484042917

In [38]:
def cal_mean_feature_importance(models):
    importance_avg = None
    
    for model in models:
        importance_df = model.print_feature_importance()
        if importance_avg is None:
            importance_avg = importance_df.copy()
        else:
            importance_avg['Importance'] += importance_df['Importance']
    
    importance_avg['Importance'] /= len(models)
    
    importance_avg = importance_avg.sort_values(by='Importance', ascending=False).reset_index(drop=True)
    return importance_avg
    
importance_avg = cal_mean_feature_importance(models_cb)
importance_avg

          Group  Importance
0       모터_연대율2    1.469718
1      모터_평균착순점    1.397017
2       모터_연대율3    1.384544
3          전일성적    1.345556
4            등급    1.025342
5    PCA_코스성적_1    0.982709
6   최근6회차_평균착순점    0.914922
7    연간성적_평균착순점    0.785096
8    최근6회차_평균득점    0.782308
9      연간성적_연대율    0.697521
10     보트_평균착순점    0.623761
11   최근6회차_연대율2    0.615807
12   최근6회차_연대율3    0.569822
13     최근3경기_평균    0.539976
14     최근6회차_승률    0.531200
15       보트_연대율    0.486695
16        코스_성적    0.462490
17   최근6회차_평균ST    0.450594
18           체중    0.404348
19   PCA_코스성적_2    0.359351
20           나이    0.292479
21         출주횟수    0.287969
22        평균사고점    0.224788
23                 0.030893
24           성별    0.022356

- Test 데이터

### RF

In [22]:
train = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))

unique_race_ids = train['Race_ID'].unique()
kf = KFold(n_splits=5, shuffle=True, random_state=seed)

# smote_strategies = []
# smote_strategies.append(0.9)
# smote_strategies.append(0.8)
# smote_strategies.append(0.6)
# smote_strategies.append(0.5)
# smote_strategies.append(0.4)
# smote_strategies.append(0.3)

models_rf = []
scores = []
for i, (train_race_ids, val_race_ids) in enumerate(kf.split(unique_race_ids)):
    train_ids = unique_race_ids[train_race_ids]
    val_ids = unique_race_ids[val_race_ids]

    train_fold = train[train['Race_ID'].isin(train_ids)].reset_index(drop=True)
    val_fold = train[train['Race_ID'].isin(val_ids)].reset_index(drop=True)

    X_train, y_train, X_val, y_val = all_process(train_fold, val_fold, target=target_value, is_train=True)

    params_list = cal_rf_params()
    model = custom_randomforest(params_list)
    model.fit(X_train, y_train)

    models_rf.append(model)

    y_pred = models_rf[i].predict_proba(X_val)

    accuracy = evaluate_(y_pred, y_val, target_value)
    scores.append(accuracy)
    print(f'folds {i+1}')
    print(f'Accuracy: {accuracy}')


print(f'최종 스코어: Avg. Accuracy of validset: {np.mean(scores)}, Std. Accuracy of validset: {np.std(scores)}')

folds 1
Accuracy: 0.2796915167095116
folds 2
Accuracy: 0.2647814910025707
folds 3
Accuracy: 0.26632390745501283
folds 4
Accuracy: 0.27249357326478146
folds 5
Accuracy: 0.26440329218106995
최종 스코어: Avg. Accuracy of validset: 0.2695387561225893, Std. Accuracy of validset: 0.005850629114058838

In [23]:
importance_avg = cal_mean_feature_importance(models_rf)
importance_avg

          Group  Importance
0    PCA_코스성적_1    0.010254
1      모터_평균착순점    0.010227
2       모터_연대율2    0.009876
3    PCA_코스성적_2    0.009777
4       모터_연대율3    0.009673
5   최근6회차_평균착순점    0.008816
6    최근6회차_평균득점    0.008770
7    연간성적_평균착순점    0.008272
8      보트_평균착순점    0.007833
9        보트_연대율    0.007722
10           나이    0.007088
11   최근6회차_연대율3    0.007058
12   최근6회차_연대율2    0.006737
13     연간성적_연대율    0.006658
14   최근6회차_평균ST    0.006480
15        코스_성적    0.006334
16         출주횟수    0.006189
17           체중    0.006117
18     최근6회차_승률    0.005699
19        평균사고점    0.005184
20     최근3경기_평균    0.004976
21         전일성적    0.003558
22           등급    0.002713
23           성별    0.000593
24                 0.000181

In [39]:
train = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))
test = pd.read_csv(os.path.join(ROOT_DIR, "test.csv"))

y_test_for_연승 = cal_y_val_for_연승(train, test)
y_test_for_연승 = np.array(y_test_for_연승)

In [40]:
race_id = test[['Race_ID']].copy()
race_id_unique = race_id.drop_duplicates().reset_index(drop=True)

In [41]:
unique_race_ids = train['Race_ID'].unique()
kf = KFold(n_splits=5, shuffle=True, random_state=seed)

all_predictions_cb = []
for i, (train_race_ids, val_race_ids) in enumerate(kf.split(unique_race_ids)):
    train_ids = unique_race_ids[train_race_ids]

    train_fold = train[train['Race_ID'].isin(train_ids)].reset_index(drop=True)
    test_fold = test.copy()

    X_train, y_train, X_test, y_test = all_process(train_fold, test_fold, target=target_value, is_train=True)

    y_pred_cb = models_cb[i].predict_proba(X_test)
    all_predictions_cb.append(y_pred_cb)

mean_pred_cb = np.mean(all_predictions_cb, axis=0)
if target_value != '복승':
    mean_pred_cb = mean_pred_cb / mean_pred_cb.sum(axis=1, keepdims=True)

y_test = np.array(y_test)
accuracy, 연승_score = evaluate_(mean_pred_cb, y_test, target_value, contain_연승=True, y_val_연승=y_test_for_연승)

print(f'최종 스코어: Accuracy of testset: {accuracy}, 연승 적중률: Accuracy of testset: {연승_score}')

최종 스코어: Accuracy of testset: 0.2849264705882353, 연승 적중률: Accuracy of testset: 0.6681985294117647

In [34]:
unique_race_ids = train['Race_ID'].unique()
kf = KFold(n_splits=5, shuffle=True, random_state=seed)

all_predictions_rf = []
for i, (train_race_ids, val_race_ids) in enumerate(kf.split(unique_race_ids)):
    train_ids = unique_race_ids[train_race_ids]

    train_fold = train[train['Race_ID'].isin(train_ids)].reset_index(drop=True)
    test_fold = test.copy()

    X_train, y_train, X_test, y_test = all_process(train_fold, test_fold, target=target_value, is_train=True)

    y_pred_rf = models_rf[i].predict_proba(X_test)
    all_predictions_rf.append(y_pred_rf)

mean_pred_rf = np.mean(all_predictions_rf, axis=0)
if target_value != '복승':
    mean_pred_rf = mean_pred_rf / mean_pred_rf.sum(axis=1, keepdims=True)

y_test = np.array(y_test)
accuracy, 연승_score = evaluate_(mean_pred_rf, y_test, target_value, contain_연승=True, y_val_연승=y_test_for_연승)

print(f'최종 스코어: Accuracy of testset: {accuracy}, 연승 적중률: Accuracy of testset: {연승_score}')

최종 스코어: Accuracy of testset: 0.2711397058823529, 연승 적중률: Accuracy of testset: 0.6691176470588235

In [35]:
mean_pred = (mean_pred_cb + mean_pred_rf) / 2

y_test = np.array(y_test)
accuracy, 연승_score = evaluate_(mean_pred, y_test, target_value, contain_연승=True, y_val_연승=y_test_for_연승)

print(f'최종 스코어: Accuracy of testset: {accuracy}, 연승 적중률: Accuracy of testset: {연승_score}')

최종 스코어: Accuracy of testset: 0.27849264705882354, 연승 적중률: Accuracy of testset: 0.6654411764705882

In [135]:
pd.DataFrame(mean_pred, columns=['1번', '2번', '3번', '4번', '5번', '6번'])

            1번        2번        3번        4번        5번        6번
0     0.330745  0.204855  0.179442  0.127167  0.065141  0.092650
1     0.243238  0.199895  0.315870  0.072328  0.156935  0.011735
2     0.329255  0.270028  0.206466  0.119977  0.038387  0.035886
3     0.429965  0.308791  0.109290  0.056959  0.085995  0.008999
4     0.319250  0.211408  0.243234  0.125818  0.061081  0.039209
...        ...       ...       ...       ...       ...       ...
1027  0.395945  0.089820  0.095773  0.171510  0.246297  0.000656
1028  0.427923  0.310202  0.044439  0.109751  0.087406  0.020281
1029  0.511534  0.331300  0.035404  0.090000  0.030955  0.000807
1030  0.434724  0.248380  0.141987  0.131950  0.041165  0.001794
1031  0.432057  0.292917  0.138733  0.042344  0.051488  0.042460

[1032 rows x 6 columns]

In [136]:
mean_pred_복승 = pd.concat([race_id_unique, pd.DataFrame(mean_pred, columns=['1번', '2번', '3번', '4번', '5번', '6번'])], axis=1)
mean_pred_복승

           Race_ID        1번        2번        3번        4번        5번        6번
0       2024_1_1_1  0.330745  0.204855  0.179442  0.127167  0.065141  0.092650
1       2024_1_1_2  0.243238  0.199895  0.315870  0.072328  0.156935  0.011735
2       2024_1_1_3  0.329255  0.270028  0.206466  0.119977  0.038387  0.035886
3       2024_1_1_4  0.429965  0.308791  0.109290  0.056959  0.085995  0.008999
4       2024_1_1_5  0.319250  0.211408  0.243234  0.125818  0.061081  0.039209
...            ...       ...       ...       ...       ...       ...       ...
1027  2024_36_2_12  0.395945  0.089820  0.095773  0.171510  0.246297  0.000656
1028  2024_36_2_13  0.427923  0.310202  0.044439  0.109751  0.087406  0.020281
1029  2024_36_2_14  0.511534  0.331300  0.035404  0.090000  0.030955  0.000807
1030  2024_36_2_15  0.434724  0.248380  0.141987  0.131950  0.041165  0.001794
1031  2024_36_2_17  0.432057  0.292917  0.138733  0.042344  0.051488  0.042460

[1032 rows x 7 columns]

In [137]:
mean_pred_복승.to_csv(f'./단승_확률값.csv', index=False, encoding='utf-8-sig')

In [148]:
train = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))
test = pd.read_csv(os.path.join(ROOT_DIR, "test.csv"))

X_train, y_train, X_test, y_test = all_process(train, test, target='삼복승', is_train=True, is_dddd=True)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(9724, 152) (9724, 6) (1088, 152) (1088, 6)

In [82]:
y_test

      삼복승_1번선수  삼복승_2번선수  삼복승_3번선수  삼복승_4번선수  삼복승_5번선수  삼복승_6번선수
0          0.0       3.0       2.0       0.0       1.0       0.0
1          2.0       0.0       1.0       0.0       0.0       3.0
2          0.0       2.0       3.0       0.0       0.0       1.0
3          1.0       0.0       0.0       0.0       2.0       3.0
4          1.0       0.0       0.0       2.0       0.0       3.0
...        ...       ...       ...       ...       ...       ...
1027       2.0       3.0       0.0       0.0       1.0       0.0
1028       0.0       1.0       2.0       3.0       0.0       0.0
1029       1.0       2.0       0.0       0.0       3.0       0.0
1030       1.0       2.0       0.0       0.0       3.0       0.0
1031       1.0       2.0       0.0       3.0       0.0       0.0

[1032 rows x 6 columns]

In [83]:
y_test.to_csv(f'./삼복승_순위값.csv', index=False, encoding='utf-8-sig')

- Base_line_단승:  Accuracy of testset: 0.4532940019665683
- 

## 복승
- 최종 스코어: Accuracy of testset: 0.2693798449612403, 연승 적중률: Accuracy of testset: 0.6821705426356589 (범주형 변수 변환(등급, 나이))
- 최종 스코어: Accuracy of testset: 0.2751937984496124, 연승 적중률: Accuracy of testset: 0.6724806201550387 (범주형 변수 변환(등급, 나이)) 파라미터 optuna로 조정

- RF
- 최종 스코어: Accuracy of testset: 0.2761627906976744, 연승 적중률: Accuracy of testset: 0.6560077519379846

- 앙상블
- 최종 스코어: Accuracy of testset: 0.2800387596899225, 연승 적중률: Accuracy of testset: 0.6666666666666666


### 삼복승
- Base_line_삼복승: Accuracy of testset: 0.18682399213372664

# 실제 경기 예측

In [42]:
from crawlling_entry import crawl_race_entries

연도 = 2024
회차 = 37
일차 = 2
sub = crawl_race_entries(연도, 회차, 일차)
for col in sub.columns:
    try:
        sub[col] = sub[col].astype(float)
    except:
        continue

day_ord = sub[['경주번호']].astype(int)
day_ord.drop_duplicates(inplace=True)
day_ord['경주번호'] = day_ord['경주번호'].astype(str) + '경기'

sub['Race_ID'] = sub.apply(lambda row: f"{int(row['연도'])}_{int(row['회차'])}_{int(row['일차'])}_{int(row['경주번호'])}", axis=1)
sub

Skipping race: 2024 37 2 1 due to error: list index out of range

,연도,회차,일차,경주번호,경기종류,번호,등급,기수,선수명,성별,...,모터_평균착순점,모터_연대율2,모터_연대율3,전탑승선수1,전탑승선수2,보트번호,보트_평균착순점,보트_연대율,특이사항,Race_ID
0,2024.0,37.0,2.0,2.0,플라잉,1.0,B2,4.0,어선규,남,...,5.38,33.3,53.8,박민영/332,정인교/356,19.0,4.94,34.3,,2024_37_2_2
1,2024.0,37.0,2.0,2.0,플라잉,2.0,A2,7.0,윤동오,남,...,5.87,38.5,64.1,사재준/155,이주영/4222,16.0,5.21,26.3,,2024_37_2_2
2,2024.0,37.0,2.0,2.0,플라잉,3.0,A2,1.0,김창규,남,...,5.68,40.0,60.0,윤상선/356,주은석/12,9.0,6.53,56.3,,2024_37_2_2
3,2024.0,37.0,2.0,2.0,플라잉,4.0,B2,14.0,김은지,여,...,6.37,50.0,60.0,조규태/564,박준호/421,55.0,4.53,35.3,,2024_37_2_2
4,2024.0,37.0,2.0,2.0,플라잉,5.0,B2,3.0,이지수,여,...,5.85,44.4,59.3,장수영/242,김승택/435,93.0,4.19,25.8,F 후 출전,2024_37_2_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91,2024.0,37.0,2.0,17.0,온라인,2.0,B1,1.0,오세준,남,...,5.68,37.8,56.8,염윤정/44,이재학/114,67.0,5.77,46.2,,2024_37_2_17
92,2024.0,37.0,2.0,17.0,온라인,3.0,B1,4.0,구현구,남,...,4.26,23.5,35.3,김재윤/666,문주엽/3555,3.0,6.57,52.2,,2024_37_2_17
93,2024.0,37.0,2.0,17.0,온라인,4.0,A2,11.0,전정환,남,...,4.74,32.3,45.2,이경섭/53,조규태/561,87.0,6.96,56.5,F 후 출전,2024_37_2_17
94,2024.0,37.0,2.0,17.0,온라인,5.0,A1,1.0,서화모,남,...,5.08,35.1,48.6,서종원/565,박준호/465,29.0,6.67,45.8,,2024_37_2_17
95,2024.0,37.0,2.0,17.0,온라인,6.0,B2,16.0,이수빈,여,...,6.71,44.1,73.5,김민천/113,김지현/24,60.0,4.47,26.7,,2024_37_2_17

In [43]:
train = pd.read_csv(os.path.join(ROOT_DIR, "train.csv"))

unique_race_ids = train['Race_ID'].unique()
kf = KFold(n_splits=5, shuffle=True, random_state=seed)

all_predictions_cb = []
all_predictions_rf = []
for i, (train_race_ids, val_race_ids) in enumerate(kf.split(unique_race_ids)):
    train_ids = unique_race_ids[train_race_ids]

    train_fold = train[train['Race_ID'].isin(train_ids)].reset_index(drop=True)
    test_fold = sub.copy()

    X_train, y_train, X_test = all_process(train_fold, test_fold, target=target_value, is_train=False)

    y_pred_cb = models_cb[i].predict_proba(X_test)
    all_predictions_cb.append(y_pred_cb)

    y_pred_rf = models_rf[i].predict_proba(X_test)
    all_predictions_rf.append(y_pred_rf)

mean_pred_cb = np.mean(all_predictions_cb, axis=0)
mean_pred_cb = mean_pred_cb / mean_pred_cb.sum(axis=1, keepdims=True)

mean_pred_rf = np.mean(all_predictions_rf, axis=0)
mean_pred_rf = mean_pred_rf / mean_pred_rf.sum(axis=1, keepdims=True)

mean_pred = (mean_pred_cb + mean_pred_rf) / 2

mean_pred_df = pd.DataFrame(mean_pred)
mean_pred_df.index = day_ord['경주번호'].values
mean_pred_df.columns = [f"{i+1}번" for i in range(mean_pred_df.shape[1])]
mean_pred_df = mean_pred_df.div(mean_pred_df.sum(axis=1), axis=0)
mean_pred_df

            1번        2번        3번        4번        5번        6번
2경기   0.339405  0.213242  0.195988  0.103693  0.071687  0.075984
3경기   0.226732  0.156548  0.087158  0.230768  0.121175  0.177618
4경기   0.259246  0.294490  0.282277  0.046332  0.077851  0.039804
5경기   0.404161  0.111955  0.114619  0.086017  0.128007  0.155241
6경기   0.253119  0.177309  0.076109  0.174170  0.178019  0.141274
7경기   0.121794  0.232311  0.221158  0.249025  0.084252  0.091460
8경기   0.300114  0.173324  0.151000  0.082466  0.222028  0.071068
9경기   0.277617  0.143966  0.254582  0.143765  0.076829  0.103240
10경기  0.192279  0.361713  0.118608  0.129317  0.074813  0.123269
11경기  0.276112  0.039256  0.207959  0.175122  0.177738  0.123813
12경기  0.315627  0.147301  0.127022  0.111135  0.236817  0.062099
13경기  0.133258  0.331253  0.193518  0.114055  0.083545  0.144370
14경기  0.244265  0.080838  0.244065  0.181645  0.147503  0.101683
15경기  0.255911  0.158683  0.266496  0.067208  0.080886  0.170817
16경기  0.224017  0.081443  0.321988  0.139518  0.163627  0.069405
17경기  0.316129  0.170789  0.093056  0.144993  0.127771  0.147262

In [187]:
mean_pred_df.to_excel(f'./result/{연도}_{회차}_{일차}_{target_value}.xlsx', index=True, float_format="%.3f")

In [188]:
mean_pred_df.to_csv(f'./result/{연도}_{회차}_{일차}_{target_value}_scaling.csv', index=False, encoding='utf-8-sig')